name: gotools

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Test:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x, go1.18.x]
        os: [ubuntu-latest, windows-latest, macos-11]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Test 
      run: go test -v ./...
  
